### ISSUE TITLE
Something in `convert_italy.py` casts some columns to float

### ISSUE THREAD

**Issue by wolfgang-noichl** [satzvonrolle/datavsvirus#2]
There's a cast to float in the tests dealing with this, which should be removed as well.

**Comment by elcolumbio** [comment]
i found something.
In the raw data in the file italy_0311.csv this row has a missing value for cases:
2020-03-11 17:00:00 | ITA | 19 | Sicilia | 994 | In fase di definizione/aggiornamento |   | 0 | 0 | 
Numpy cant have Nones and Integer dtypes together, so it is a float. This maybe the only case so do we 0 fill None?

**Comment by satzvonrolle** [comment]
You're right! I would actually propose for now to remove the rows with the entry "In fase di definizione/aggiornamento" (probably means something like "Being finalised/updated") entirely. These seem to be some intermediate values that could not be attributed to a actual province.. @ChristophJud89 can you help us out with what these rows mean exactly?
